DROP DATABASE IF EXISTS mcla_two;

CREATE DATABASE mcla_two;

USE mcla_two;

CREATE TABLE two_letters(
id INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (id),
words VARCHAR(10) NOT NULL
);

CREATE TABLE three_letters(
id INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (id),
words VARCHAR(10) NOT NULL
);

CREATE TABLE four_letters(
id INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (id),
words VARCHAR(10) NOT NULL
);

CREATE TABLE five_letters(
id INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (id),
words VARCHAR(10) NOT NULL
);

CREATE TABLE six_letters(
id INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (id),
words VARCHAR(10) NOT NULL
);

CREATE TABLE seven_letters(
id INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (id),
words VARCHAR(10) NOT NULL
);

CREATE TABLE eight_letters(
id INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (id),
words VARCHAR(10) NOT NULL
);
